spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false&autoReconnect=true
  jpa:
    show-sql: true